[package]
name = "p2p-swarm"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
p2p-identity = { path = "../p2p-identity" }
p2p-mux = { path = "../p2p-mux" }
p2p-protocol = { path = "../p2p-protocol" }
p2p-transport = { path = "../p2p-transport" }
tokio.workspace = true
tracing.workspace = true
[dev-dependencies]
yamux.workspace = true
tokio-util = { workspace = true, features = ["compat"] }