[package]
name = "p2p-transport"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
tokio.workspace = true
tokio-util.workspace = true
thiserror.workspace = true
tracing.workspace = true
quinn.workspace = true
p2p-identity = { path = "../p2p-identity" }
p2p-mux = { path = "../p2p-mux" }
p2p-security = { path = "../p2p-security" }
